TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'DL.Gallery': TRUE
    userInterface:
      translation:
        autoInclude:
          'DL.Gallery': ['NodeTypes/*']
      inspector:
        dataTypes:
          'TYPO3\Media\Domain\Model\AssetCollection':
            typeConverter: 'TYPO3\Neos\TypeConverter\EntityToIdentityConverter'
            editor: 'TYPO3.Neos/Inspector/Editors/SelectBoxEditor'
            editorOptions:
              dataSourceIdentifier: 'dl-gallery-assetcollections'

DL:
  Gallery:

    loadGalleryCSS: true
    loadGalleryJS: true

    themes:
      bootstrapLightbox:
        label: 'Bootstrap with Lightbox'
        themeSettings:
          galleryCSS: 'resource://DL.Gallery/Public/Styles/BootstrapLightbox.css'
          galleryJS: 'resource://DL.Gallery/Public/JavaScript/BootstrapLightbox.min.js'

          columnClass: 'col-md-4'
          imageVariants:
            thumb:
              maximumWidth:
              maximumHeight:
              width: 500
              height: 500
              allowCropping: true
              allowUpScaling:
            large:
              maximumWidth: 2000
              maximumHeight: 1200
              width:
              height:
              allowCropping:
              allowUpScaling:

      justified:
        label: 'Justified Gallery'
        themeSettings:
          galleryCSS: 'resource://DL.Gallery/Public/Styles/JustifiedGallery.css'
          galleryJS: 'resource://DL.Gallery/Public/JavaScript/JustifiedGallery.min.js'
          imageVariants:
            thumb:
              maximumWidth: 800
              maximumHeight: 800
            large:
              maximumWidth: 2000
              maximumHeight: 1200